### ISSUE TITLE
Allow translators to Pull request updated files

### ISSUE THREAD

**Issue by mateunho** [peazip/PeaZip-Translations#1]
If there's already a repo for translations, it would be nice if translators could file a PR with updates.

> follow-up on [PeaZip issue #2](https://github.com/giorgiotani/PeaZip/issues/2) by @lmy441900
> 
> CC @giorgiotani

**Comment by peazip** [comment]
Directory lang (main application's texts) and lang-wincontext (texts for Windows context menu) are now available in PeaZip's Git repository https://github.com/peazip/PeaZip/tree/sources/peazip-sources/res/share
This dedicated Translations repository, with packages for translators, is still maintained as alternative way to contribute translations.
