### ISSUE TITLE
Chinese Translate

### ISSUE THREAD

**Issue by namoen0301** [peazip/PeaZip-Translations#2]
https://drive.google.com/open?id=0B9Qm978p4Cb2MDk1MjJ1WmZvcjQ

Included txt and reg file.

**Comment by jyhi** [comment]
@wbsdty331 

https://github.com/lmy441900/peazip-l10n-zh-cn

Just now we migrated it to https://github.com/AOSC-Dev/translations/tree/master/PeaZip

**Comment by peazip** [comment]
Hello, mow it is also possible to directly update language files and Windows context menu localization from PeaZip project's Git:
https://github.com/peazip/PeaZip/tree/sources/peazip-sources/res/share
