### ISSUE TITLE
Translation platform

### ISSUE THREAD

**Issue by aha999** [peazip/PeaZip-Translations#6]
I think that the reason the PeaZip is not translated into my language yet is, that i didn't find any translation platform linked, meaning anyone that wants to translate has to do it the old fashioned complex-ish way.

I would recommend you check out [Weblate](https://weblate.org/), it is a popular translation platform, that makes it simple for anyone to translate software like PeaZip etc. For open source projects like yours, they host translations for free., so it doesn't cost you anything. There are also other platforms, but Weblate is open source and you can also self-host it if you wanted to. You can also use fancy "translated" graphs, showing which languages are translated. It's set up [here](https://hosted.weblate.org/hosting/) for FOSS projects.

So, please link PeaZip to a translation platform, so we can start to translate in a straightforward and user friendly manner.

**Comment by ViktorOn** [comment]
Thank you. But maybe it's worth closing this question already?
